sky:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
# 阿里云OSS对象存储服务配置
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tHzX4fMjySKcCoCvYci
    accessKeySecret: vPKhVa4Kux8jUP6fU4614CQ3FW0wiC
    bucketName: cangqiongwaimaipbj
#  Redis数据库配置
  redis:
    host: localhost
    port: 6379
    password: 123456

